name: Deploy to GitHub Pages


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Installing npm dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Deploy
        run: mkdir -p out
      - name: starting deploy
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: https://alwarg.github.io/fingerprinted-css/
